config/routes.rb
Admin::Application.routes.draw do
  resources :categories

  resources :testimonies

  devise_for :users
  resources :posts, except: [:index]
  resources :images
  resources :videos
  
  get "pages/index"
  
  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  

end

app/models/testimony.rb
class Testimony < ActiveRecord::Base
  belongs_to :post, inverse_of: :testimonies
  validates :author, :content, presence: true
end

app/controllers/testimonies_controller.rb
class TestimoniesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_testimony, only: [:show, :edit, :update, :destroy]
  
  # GET /testimonies
  # GET /testimonies.json
  def index
    @testimonies = Testimony.all
  end

  # GET /testimonies/1
  # GET /testimonies/1.json
  def show
  end

  # GET /testimonies/new
  def new
    @testimony = Testimony.new
  end

  # GET /testimonies/1/edit
  def edit
  end

  # POST /testimonies
  # POST /testimonies.json
  def create
    @testimony = Testimony.new(testimony_params)
    if @testimony.save
      redirect_to @testimony, notice: 'Testimony was successfully created.'
    else
      render action: 'new' 
    end
  end

  # PATCH/PUT /testimonies/1
  # PATCH/PUT /testimonies/1.json
  def update
    if @testimony.update(testimony_params)
      redirect_to @testimony, notice: 'Testimony was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /testimonies/1
  # DELETE /testimonies/1.json
  def destroy
    @post = @testimony.post 
    @testimony.destroy
    redirect_to @post, notice: 'Testimony was successfully deleted.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_testimony
      @testimony = Testimony.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimony_params
      params.require(:testimony).permit(:author, :content)
    end
end

app/views/testimonies/_form.html.haml
= form_for @testimony do |f|
  - if @testimony.errors.any?
    #error_explanation
      %h2= "#{pluralize(@testimony.errors.count, "error")} prohibited this testimony from being saved:"
      %ul
        - @testimony.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/testimonies/edit.html.haml
%h1 Editing testimony

= render 'form'

= link_to 'Show', @testimony
\|
= link_to 'Back', testimonies_path

app/views/testimonies/index.html.haml
%h1 Listing testimonies

%table
  %tr
    %th
    %th
    %th

  - @testimonies.each do |testimony|
    %tr
      %td= testimony.content
      %td= link_to 'Show', testimony
      %td= link_to 'Edit', edit_testimony_path(testimony)
      %td= link_to 'Destroy', testimony, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/testimonies/new.html.haml
%h1 New testimony

= render 'form'

= link_to 'Back', testimonies_path

app/views/testimonies/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_testimony_path(@testimony)
\|
= link_to 'Back', testimonies_path