config/routes.rb
Admin::Application.routes.draw do
  resources :categories

  resources :testimonies

  devise_for :users
  resources :posts, except: [:index]
  resources :images
  resources :videos
  
  get "pages/index"
  
  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, inverse_of: :posts
  belongs_to :category, inverse_of: :posts

  has_many :testimonies, inverse_of: :post, dependent: :destroy
  has_many :images, inverse_of: :post, dependent: :destroy

  accepts_nested_attributes_for :images
  accepts_nested_attributes_for :testimonies

  validates :title, :venue, :description, presence: true

  scope :videos, -> { where.not( video: [nil, ""]) }
  scope :images, -> { joins(:images).group('post_id') }

  def self.search(search)
    if search
      where("title like ?", search)
    else
      Post.all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:show, :edit, :update, :destroy]  

  def show
    @images = @post.images
    @testimonies = @post.testimonies
  end

  def new
     @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)

    begin
      Post.transaction do
        @post.save!
        if params[:images]
          params[:images].each do |image_file|
            @image = @post.images.create!(file: image_file, post_id: @post.id)
          end
        end
      end
      redirect_to @post, notice: 'Post was successfully created.'
    rescue ActiveRecord::RecordInvalid
      render action: 'new', status: :unprocessable_entity
    end
  end

  def edit
    @images = @post.images
  end

  def update   
    if @post.update_attributes(post_params)
      if params[:images]
        params[:images].each do |image|
          @image = @post.images.create!(file: image, :post_id => @post.id)           
        end
      end
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to pages_index_path, notice: 'Post was successfully deleted.'
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def find_post
      @post = Post.find(params[:id])
    end

    # Only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :video, :venue, :category_id, images_attributes: [:id, :post_id, :file], testimonies_attributes: [:id, :author, :content])
    end
end

app/views/posts/_form.html.haml
= nested_form_for @post, :html => { :class => 'form-horizontal', :id => "fileupload"} do |f| 
  .control-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title, class: 'text_field' 
  .control-group
    = f.label :venue, class: 'control-label' 
    .controls
      = f.text_field :venue, class: 'text_field'

  - @categories = Category.all 
  
  - if !@categories.blank? 
    .control-group
      = f.label :category, class: 'control-label' 
      .controls
        = select("post", "category_id", @categories.collect {|c| [ c.title, c.id ] }) 
  .control-group
    = f.label :video, class: 'control-label'
    .controls
      = f.text_field :video, class: 'text_field'
  .control-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_area :description, class:'text_field'

  = f.fields_for :testimonies do |testimony| 
    = f.label :author, class: 'control-label' 
    %br
    = testimony.text_field :author 
    %br
    = f.label :content, class: 'control-label' 
    %br
    = testimony.text_area :content 
    %br
    = testimony.link_to_remove "Remove this testimony" 

  %p
    = f.link_to_add "Add a testimony", :testimonies
    
  #images.row
    .fileupload-buttonbar
      .progressbar.fileupload-progressbar.nofade
        %div{style: "width:0%;"}
      %span{class: "btn btn-mini fileinput-button"}
        %i{class: "icon-plus"}
        %span= t('photos.add_files') 
        = f.fields_for :post_images do |p| 
          .field
            = p.file_field :file, multiple: true, name: "images[]" 

  - if params[:controller] == "posts" && params[:action] == "edit" && !@images.blank?  
    - @images.each do |image| 
      = image_tag image.file, size: "150x150"
   
  %table{ role: "presentation", class: "table table-striped" }
    %tbody{class: "files"}

  .form-actions
    = f.submit nil, class: 'btn btn-mini btn-primary', id: "upload" 
    = link_to t('.cancel', default: t("helpers.links.cancel")), pages_index_path, class: 'btn btn-mini'

:plain
  <!-- The template to display files available for upload -->
  <script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
      <td class="preview"><span class="fade"></span></td>
      <td class="name"><span>{%=file.name%}</span></td>
      <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    </tr>    
    {% } %}
  </script>

  <!-- The template to display files available for download -->
  <script id="template-download" type="text/x-tmpl">  
  </script>

app/views/posts/edit.html.haml
- model_class = @post.class
.page-header
  %h1= t '.title', default: t('helpers.titles.edit', model: model_class.model_name.human, default: "Edit #{model_class.model_name.human}")
= render :partial => 'form'

app/views/posts/new.html.haml
- model_class = @post.class
.page-header
  %h1= t '.title', default: t('helpers.titles.new', model: model_class.model_name.human, default: "New #{model_class.model_name.human}")
= render partial: 'form' 

app/views/posts/show.html.haml
%p
  %strong Title:
  = @post.title 
  %br
  - if @post.category
    %strong Category:
    = @post.category.title.capitalize
- @testimonies.each do |testimony| 
  =testimony.author.capitalize
  =link_to "Destroy", testimony, method: :delete
  %br
- @images.each do |images| 
  .col-md-4
    =image_tag images.file_url, :size => "200x200" 
    %br
    =link_to "Edit", edit_image_path(images) 
    | 
    =link_to "Destroy", images, method: :delete

=link_to 'Edit', edit_post_path(@post) 
|
=link_to 'Destroy', @post, method: :delete 
|
=link_to 'Back', pages_index_path 