config/routes.rb
Admin::Application.routes.draw do
  resources :categories

  resources :testimonies

  devise_for :users
  resources :posts, except: [:index]
  resources :images
  resources :videos
  
  get "pages/index"
  
  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :gender, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :gender, :password, :password_confirmation, :current_password) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end
  
  def action?(*action)
    action.include?(params[:action])
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge( sort: column, direction: direction, page: nil ), { class: css_class }
  end
end

app/views/application/_menu_bar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container-fluid.container
    .navbar-header
      %button.navbar-toggle{type: "button", "data-toggle" => "collapse", "data-target" => "#bs"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: pages_index_path} 
        = image_tag("logo.png", alt: "Logo", width: 25, height: 25)

    .collapse.navbar-collapse#bs
      %ul.nav.navbar-nav
        %li{ :class => ('active' if current_page?(pages_index_path)) }
          = link_to 'Home', pages_index_path                  
        %li.dropdown
          %a.dropdown-toggle{href: "#", "data-toggle" => "dropdown"} 
            = current_user.username.capitalize 
            %b.caret
          %ul.dropdown-menu
            %li
              %a{ href: edit_user_registration_path } 
                Edit my data          
        %li{ :class => ('active' if controller?("images")) }
          = link_to 'Images', images_path
        %li{ :class => ('active' if controller?("videos")) }
          = link_to 'Videos', videos_path
        %li{ :class => ('active' if controller?("categories")) }
          = link_to 'Categories', categories_path
        %li{ :class => ('active' if controller?("testimonies")) }
          = link_to 'Testimonies', testimonies_path
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Sign Out', destroy_user_session_path, method: "delete"